### ISSUE TITLE
空白類文字について（「スペース」「空白」などの見直し）

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#103]
空白類文字についての説明をどうするか検討する。

**Comment by momdo** [comment]
https://infra.spec.whatwg.org/#ascii-whitespace で定義されている
ASCII whitespaceに言及するとか？

> ASCII whitespace is U+0009 TAB, U+000A LF, U+000C FF, U+000D CR, or U+0020 SPACE.

**Comment by bakera** [comment]
文中に空白類文字について言及しているところが結構あるので後で調整する
いったん「空白類文字」にしているつもりだが「スペース」などと書いている箇所があるかも。

**Comment by bakera** [comment]
2-2では
>属性の前後は、「ASCII空白文字」(ASCII whitespace)で区切ります。

2-8では
>空白類文字 (スペース、タブ、改行など) → 属性値との区切りと解釈されます

**Comment by bakera** [comment]
ちなみに「空白類文字」というのはHTML4の日本語訳の時に議論して決めた訳語で、「tabなども含まれるので空白ではなく空白類としたい」というような話があったように記憶しています。とはいえ割と独自用語感はあるんですよね。

**Comment by bakera** [comment]
「ASCII空白文字」(ASCII whitespace)で統一する方向にしたいと思いつつあります。

**Comment by momdo** [comment]
https://github.com/bakera/html-book/pull/398#pullrequestreview-817372251

> あと「スペース」「空白」やそれに類する単語は全部洗い出す必要があるかも。

ということでタイトルを変えておきました。

**Comment by momdo** [comment]
ASCII空白文字で統一できているはずなので閉じておきます
