### ISSUE TITLE
表記揺れ

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#106]
表記揺れについて調整する必要がある。
たとえば、ブラウザvsブラウザー、ユーザvsユーザーなど。
一通り書けたところでまとめて実施するのが良い

**Comment by bakera** [comment]
文字エンコーディング vs 文字符号化方式

DOCTYPE vs 文書型宣言については、
- HTML5のもの = DOCTYPE
- 過去のHTMLのもの = 文書型宣言
としたい気持ち (いまは統一できていないです)

**Comment by momdo** [comment]
See also #29, #30

**Comment by kyokoseki** [comment]
表記揺れについては、基本的には編集側で構成時にチェックしますが、事前に基準を決める必要があるかと思います。
基準さえ決まれば、後はある程度は置換でいけるかと

**Comment by momdo** [comment]
辿る→たどる

**Comment by momdo** [comment]
箇条書きの文末の句点はトリ

**Comment by momdo** [comment]
一部ここで取り上げたもので従っていないものもありますが、取り上げたものについては統一は出てきているので、とりあえずCloseします。
