### ISSUE TITLE
3-5 link要素 Resource Hints方面について

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#114]
- DNS-Prefetch
- Preconnect
- Prefetch
- Prerender

というようなキーワードの紹介をするのかどうか。するとすればどのくらい？

**Comment by momdo** [comment]
記載自体はする方向で。

**Comment by momdo** [comment]
以下のResource Hints由来のlinktypeは実装不足

- [link-type-modulepreload](https://html.spec.whatwg.org/multipage/#link-type-modulepreload) [HTML/Link_types/modulepreload](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/modulepreload)
- [link-type-preload](https://html.spec.whatwg.org/multipage/#link-type-preload) [HTML/Link_types/preload](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload)
- [link-type-prerender](https://html.spec.whatwg.org/multipage/#link-type-prerender) [HTML/Link_types/prerender](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/prerender)

書くなら以下か？
- [dns-prefetch](https://momdo.github.io/html/links.html#link-type-dns-prefetch)
- [prefetch](https://momdo.github.io/html/links.html#link-type-prefetch)

**Comment by bakera** [comment]
なんだかんだ3-5でガッツリ網羅してしまったので対応済みと言えば対応済み。

**Comment by momdo** [comment]
対応済みなのでClose。レビュワーからコメントあれば。
