### ISSUE TITLE
用語：HTTP応答ヘッダー

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#131]
> HTTP応答ヘッダー

HTTPレスポンスヘッダーの方がよいか？

https://github.com/bakera/html-book/pull/127#discussion_r616304994_

**Comment by bakera** [comment]
HTML4の翻訳の際には「訳して違和感ないものはできるだけ訳す」という方針で「HTTP応答ヘッダ」としていましたが、世間一般的にはHTTPレスポンスヘッダの方が優勢であるような気がします。
「HTTPレスポンスヘッダー」で統一で良いのではないでしょうか。ただ長くはなります。

**Comment by momdo** [comment]
応答にするなら、リクエストは要求ですかね（Edgeの開発者ツールは応答にしてるっぽい）。どちらに寄せるにせよ、統一しておきたいところです。
