### ISSUE TITLE
JavaScriptのサンプルコードを見直す

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#156]
https://github.com/bakera/html-book/blob/master/md_text/3-9-2.md#progress%E8%A6%81%E7%B4%A0

```html
<progress id=p max="100" value="50"><span>50</span>%</progress>
<script>
  var progressBar = document.getElementById('p');
  function updateProgress(newValue) {
    progressBar.value = newValue;
    progressBar.getElementsByTagName('span')[0].textContent = newValue;
  }
 </script>
```
たとえば`progressBar.firstElementChild.textContent`でよいのでは、など。
全般的に第三者にレビューしてもらうのがよいか。

**Comment by bakera** [comment]
`var`や`function`などが使われているけれどもモダンな書き方に統一した方が良いかも、という観点もあり。
本書はJS開設が目的ではないので、サンプルコードはブラウザの互換性重視する必要もなく、簡潔な方が良いと考えます。
その辺のポリシーを決めた方が良いのかもしれません。

**Comment by yamanoku** [comment]
全体に載ってるコードはまだ見れてないのですが、ES6の書き方に準拠するのは最低限やってもいいかなと思いました。

ひとまず `var` で変数が再度挿入されなさそうなものは `const` に統一でも良さそうです 👍🏼

**Comment by yamanoku** [comment]
`<script>` や JavaScript コードが載っているものメモ

- 2-3-2.md
- 2-4.md
- 2-7.md
- 2-8.md
- 3-5.md
- 3-9.md
- 3-10.md
- 3-11.md
- 4-1.md
- 4-2.md
- 4-4.md

**Comment by yamanoku** [comment]
セミコロンをつけるかどうか、みたいなのもありそうですね。

```js
const hoge = document.getElementById('hoge');
const fuga = document.getElementById('fuga')
```

ただ基本的にはセミコロンをつけるべし（ブロック文は除く）というものなので、セミコロンはつける方向性にしたいです。

> JavaScriptには、特殊なルールに基づき、セミコロンがない文も行末に自動でセミコロンが挿入されるという仕組みがあります。 しかし、この仕組みは構文を正しく解析できない場合に、セミコロンを足すという挙動を持っています。
https://jsprimer.net/basic/statement-expression/

**Comment by yamanoku** [comment]
[4章のサンプルコード修正プルリクエスト](https://github.com/bakera/html-book/pull/179#discussion_r718135643)にてシングルクォートで統一で良さそうとのことなので、HTML本のコード規約としてシングルクォートにしたいです

**Comment by yamanoku** [comment]
スペースをいくつ空けるかとかも考えられそう？
これは全体のHTMLのサンプルコードなどと揃えられればいいかも。

```js
<script>
  const d = document.getElementById('dialog1');
  d.showModal();
  d.onclose = () => {alert (d.returnValue)};
</script>
```

半角スペース２つ：https://github.com/bakera/html-book/blob/ed16e870db4532aa03be1f322b07fc2baab6554b/md_text/3-9.md#form%E8%A6%81%E7%B4%A0

```js
<script>
const d = document.getElementById('dialog1');
const dialogOpen = () =>{
    d.showModal();
    d.onclose = () => {alert (d.returnValue)};
}
</script>
```

半角スペース４つ：https://github.com/bakera/html-book/blob/ed16e870db4532aa03be1f322b07fc2baab6554b/md_text/3-10.md#dialog%E8%A6%81%E7%B4%A0

**Comment by yamanoku** [comment]
細かいとことだと半角スペース入れるようにするとかもですかね。
https://github.com/bakera/html-book/blob/ed16e870db4532aa03be1f322b07fc2baab6554b/md_text/4-2.md#aria%E3%83%AB%E3%83%BC%E3%83%AB3-%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%A9%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96%E3%81%AA%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AD%E3%83%BC%E3%83%AB%E3%81%AF%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89%E6%93%8D%E4%BD%9C%E5%8F%AF%E8%83%BD%E3%81%AB%E3%81%99%E3%82%8B

```js
const pushed = () =>{
```

↓

```js
const pushed = () => {
```

**Comment by bakera** [comment]
2タブか4タブかは編集側と相談ですね。原稿側ではどちらかに揃えておけばどちらでも良さそう。

**Comment by yamanoku** [comment]
JavaScript のコード内ではセミコロンをつけるで統一したいところですが、
`onclick="hoge()"` みたいな属性指定で関数よび出すものはなくてもいいのかな…

**Comment by bakera** [comment]
とりあえず現状の方針: 

- 行末のセミコロンは省略しない
- リテラルはシングルクォートでくくる
- タブ幅は2タブ
- 特定のライブラリ、フレームワークは想定しない
  - 基本的にバニラJSと標準DOM
- ES6の記法にする
  - 可能ならば var ではなくconstを、functionではなくアロー関数を使う
- 短く簡潔に書けるなら簡潔にする

**Comment by yamanoku** [comment]
> リテラルはシングルクォートでくくる

補足すると内容が文字列で取得できそうなところはシングルクオートで良さそうという感じですね。
`console.log(`hoge`);` ではなく `console.log('hoge');` で十分みたいな。

現状の方針のもとでサンプルコードの確認をすすめてみます。@bakera @momdo

**Comment by yamanoku** [comment]
#406 もマージされたことで、自分が把握しているところは終わったかなぁと思います。
追加などで漏れなどあればご指摘ください 🙏🏼

**Comment by bakera** [comment]
終わっているのでクローズします。
