### ISSUE TITLE
真偽値属性、列挙型属性などの揺れ

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#157]
3-9-2など。

揺れつつあるので、本文では一本化する。

初出時にいくつか訳語を並べる形にしたい。

**Comment by bakera** [comment]
booleanについては、「真偽値属性」という言い方だとtrue/falseという値を設定するようにも思えるのがきになっています (aria-hiddenなどは実際そうですし)。
初出時にしっかり説明して、文中では「ブール型属性」にしてしまうのもありなのでは。

**Comment by momdo** [comment]
そうですね、初出ではいくつかの訳があること触れて、あとはどれかに統一ですかね。

**Comment by sukoyakarizumu** [comment]
横からすみません。すでに把握されているかもですが、「真偽属性」と「真偽値属性」でも揺れています。少なくともどちらかはどちらかに統一した方がよさそうだなと思いました。

**Comment by bakera** [comment]
そうですね。気付いてましたがこのissueがあるので放置してました…

**Comment by momdo** [comment]
https://github.com/bakera/html-book/blob/master/md_text/2-2.md#%E3%83%96%E3%83%BC%E3%83%AB%E5%9E%8B%E5%B1%9E%E6%80%A7 にあるとおり、

- 「ブール型属性」(boolean attribute)
- 「列挙型属性」(enumerated attributes)

で本書では統一するものとして、修正します。
