### ISSUE TITLE
ARIAロールのロールの表記をどうするか

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#164]
ARIAロールの「ロール」、WCAG日本語訳に合わせるなら「役割(role)」となる

https://waic.jp/docs/UNDERSTANDING-WCAG20/ensure-compat-rsv.html

いったん単に「ロール」としておく。
合わせなくても良いという説もあるがいちおうissueにしておく

**Comment by momdo** [comment]
WCAG2で言うところの役割(role)がARIAロールに当たる、といった言及はありかも。
