### ISSUE TITLE
仕様の参照の仕方を統一する

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#165]
仕様の参照、特に仕様の途中箇所を参照している箇所について、参照の仕方を検討・統一する。
たとえば以下のようなもの。

>HTML Living Standard 4.4.4 The blockquote element [^1]
>[^1]: <https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element>

仕様名・セクション名をフルで書くのか、文中に何を残して何を脚注に入れるのか、など。

**Comment by kyokoseki** [comment]
レイアウト上では側柱のmemoとして以下のようにしています
基本的に、このように揃えていますが、イレギュラーもあります。
基本的に、sectionがあればわかると思います。
側柱は一行の文字数が少ないので、あまり長いと折り返しで読みづらくなるので。

4.4.4 The blockquote element
https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element
