### ISSUE TITLE
用語：パースするvs構文解析する

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#172]
どちらかに統一する。

構文解析器とパーサーももしあれば。

**Comment by bakera** [comment]
ちなみに、3-11の「字句解析機」は「字句解析器」の間違いなんですが、これは tokenizer の訳語で parser とはまた別のものを指しています (parserに tokenizer と tree constructor が含まれている)

**Comment by momdo** [comment]
要するにこのあたりの話ですね…
ブラウザの仕組み: 最新ウェブブラウザの内部構造
https://www.html5rocks.com/ja/tutorials/internals/howbrowserswork/

**Comment by momdo** [comment]
これ自体はカタが付いていると思うのでClose
