### ISSUE TITLE
章、節、項の呼び

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#175]
微妙にブレている気がするので、決めておく必要があるかなと。

**Comment by bakera** [comment]
これ私も気になっていました。
いまは、

1章/2章
1-1節/2-2節

のような呼びにしていたと思うのですが、ぶれていそうなので決めて統一する必要がありますね。

**Comment by momdo** [comment]
> 1章/2章
1-1節/2-2節

上記2つは私も同じ認識です。いうなればレベル3以下、例えば1-1-1ですと、
1-1-1節か、1-1-1項とするかどうかがブレてるのかなと。

**Comment by bakera** [comment]
1章/2章
1-1節/2-2節
1-1-1項/2-2-2項

ですかね? この辺は編集のご意見もお聞きしたいところ。
