### ISSUE TITLE
2-2 abbr要素に関する言及（誤植？）

### ISSUE THREAD

**Issue by sukoyakarizumu** [bakera/html-book#178]
2-2節より

> これは、title属性に以下のような値が指定された、1つのabbr要素とみなされます。
> https://github.com/bakera/html-book/blob/master/md_text/2-2.md

前後の文章とのつながりが自分にはわかりませんでした。
あと、このあとに書かれているHTMLもおそらく間違っている気がします。
（自分の解釈のミスだったらすみません！）

**Comment by bakera** [comment]
たぶん属性の引用符が前後違う場合の説明ですねこれ。
おそらく元はこんな感じの説明だったはず。

======
以下のように書いた時、

```html
<abbr title="accessibility'>a11y</abbr>
<abbr title='accessibility">a11y</abbr>
```

これは、`title`属性に以下のような値が指定された、1つの`abbr`要素とみなされます。

```text
accessibility'>a11y</abbr>
<abbr title='accessibility
```

**Comment by bakera** [comment]
どこかでこの説明が分かりにくいと判断されて削除されたがゴミが残った、という経緯のような気がします。
丸ごとトリでOKかと。

**Comment by sukoyakarizumu** [comment]
気づけてよかったです！プルリクエスト作成ありがとうございます。
