### ISSUE TITLE
属性値のみの表記について、バッククォートで囲むかダブルクォーテーションで囲むか

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#190]
>うーん...かなり悩みますが、この本は辞書的にも使われそうな気がしていて、そうするとぱっと紙面を流し見した時に、自分が検索している技術キーワードが視認しやすいのがよいと思いました。もし、バッククオートが紙面で視認しやすい強調であるならば、バッククオートで統一しても良いのかなと思いました。
>
>他の本を見てみましたが、コーディングWebアクセシビリティ・インクルーシブHTML・Form Design Patternsは、属性値のみの場合はダブルクオートはつけられていないようでした。逆に属性名=属性値のときは、属性値にダブルクオートがついていますね。
>
>タグ名・要素名・属性名・属性名＝属性値・値（キーワード）・属性値・インラインコード...については、すべて同じ強調方法（地の文とフォントが違うなど）をとっていました。
>
>ちょっとこのプルリクエストの範疇を超える話だと思うので、issueを切ったほうがよさそうですかね。

_Originally posted by @sukoyakarizumu in https://github.com/bakera/html-book/pull/181#discussion_r718911866_

**Comment by bakera** [comment]
>他の本を見てみましたが、コーディングWebアクセシビリティ・インクルーシブHTML・Form Design Patternsは、属性値のみの場合はダブルクオートはつけられていないようでした。逆に属性名=属性値のときは、属性値にダブルクオートがついていますね。

これは多分、原著がそうなのだと思います。特に変えてないはず。

**Comment by momdo** [comment]
HTML仕様を読み返して仕様では、

"`属性値`"

という具合にしているので、バッククォートで囲った上にダブルクォーテーションで囲む、という形に統一するといいのではないかと。

**Comment by momdo** [comment]
紙版ではバッククォートを使っていないのでClose
