### ISSUE TITLE
2-2/2-8 複数の属性の説明が重複している？

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#205]
@bakera そんな気がするので確認いただけるでしょうか

- https://github.com/bakera/html-book/blob/master/md_text/2-2.md#%E8%A4%87%E6%95%B0%E3%81%AE%E5%B1%9E%E6%80%A7
- https://github.com/bakera/html-book/blob/master/md_text/2-8.md#%E8%A4%87%E6%95%B0%E3%81%AE%E5%B1%9E%E6%80%A7

**Comment by bakera** [comment]
2-2のほうは複数指定できないという説明、2-8は複数指定した時にどうエラー処理されるかという説明なので、いちおう別のものではありますが、ほぼ被っているので2-8からは削除して2-2にマージしてしまって良さそうですね。

**Comment by momdo** [comment]
2-8が細かい文法の話になっているので、2-2の説明は概略に留めて、2-8に譲る格好にしてみますか
