### ISSUE TITLE
3-9-2 リード文について

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#208]
（あるいはChapter見出しも）3-9と同一だがこれでよいのか

- https://github.com/bakera/html-book/blob/master/md_text/3-9.md
- https://github.com/bakera/html-book/blob/master/md_text/3-9-2.md

**Comment by bakera** [comment]
3-9-2に関してはリード文がどうなるのかよくわからなかったので一旦放置してました。
今の組版を見ると3-9-2(3-10)のほうは以下のようにしていただいていますね。

>前セクションにつづいてフォームについての解説を行います。ここでは、 buttonやselectなどの要素について紹介します。
