### ISSUE TITLE
4-2：Using ARIAの扱いについて

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#215]
メンテされていないというのと、recharterでなんか触れてたので確認しておく

**Comment by momdo** [comment]
> recharterでなんか触れてた

言及はここ。
https://github.com/w3c/strategy/issues/282#issuecomment-934388562

Using ARIAはRetired（廃止される）扱いになりそう。
とはいえ、そのことを本文に書くのもアレなので（Using ARIAについてがっつり言及しているので）、コメントアウトとして記載か。

**Comment by bakera** [comment]
>Using ARIAについてがっつり言及しているので

それをやめるという選択肢もあるかと思います。現状はUsing ARIAの構成に寄せるためにちょっと無理して構成したところがあって、Using ARIAの紹介をやめて再構成した方がむしろスッキリするかもしれません。

**Comment by bakera** [comment]
4-2の後半に「ARIA利用時の5つのルール」としてまとまっているので、これをバラしつつ調整?

**Comment by momdo** [comment]
Using ARIAベースをARIA in HTMLとAuthoring Practicesをベースに切り替えて、漏れたものを4-4の基本テクニック（#360）に移動する感じで

**Comment by momdo** [comment]
一旦解決していると思いますのでCloseします。
