### ISSUE TITLE
WCAG ってなんだろう、について

### ISSUE THREAD

**Issue by ahomu** [bakera/html-book#223]
https://github.com/bakera/html-book/blob/f40cdab17e3f564549080df7207b71b67719187e/md_text/1-4.md#L115

ここのサラッとした言及を初出として以後 WCAG 達成基準への言及がたびたび出現しているようです。

そもそも WCAG？達成基準？みたいなところは読者の自己学習に委ねる感じでしょうか。HTML の本ということで大きい量を割く必要はないと思いますが、本書の中でも WCAG 達成基準の意味/意義などはもう少し言及してもよいのかなと思いました。

**Comment by momdo** [comment]
[デザイニングWebアクセシビリティ](https://www.borndigital.co.jp/book/5388.html)もそこまで厚く達成基準に言及しているわけではないんですよね…
