### ISSUE TITLE
WebIDLへの言及

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#227]
> ※IDLの話は仕様の読み方のところで扱う想定。

といいながら、本書では一切言及していない。

https://webidl.spec.whatwg.org/

HTML仕様には出てくる代物なので、これが何なのか簡単にでも説明したほうがよい。

**Comment by bakera** [comment]
3章冒頭の「読み方」で軽く触れる、コラム扱いでも可能

**Comment by momdo** [comment]
#444 で対応済みなのでcloseします
