### ISSUE TITLE
スクリーンリーダーのサポート状況を考慮する（abbr要素・alt属性）

### ISSUE THREAD

**Issue by sukoyakarizumu** [bakera/html-book#229]
# abbr属性

> title属性が指定されている場合、スクリーンリーダーがtitle属性の値を読み上げることが期待できます。
> [abbr要素](https://github.com/bakera/html-book/blob/3d1a0c2590c112abb67b77984e8a24d3ceb39475/md_text/3-4.md#abbr%E8%A6%81%E7%B4%A0])

abbr属性は、実際には主要なすべてのスクリーンリーダーでサポートされていないと思いますので、そのことを言及しておくのはどうでしょうか。

[abbr with title Screen reader compatibility](https://www.powermapper.com/tests/screen-readers/labelling/acronym-abbr-title/)

# alt属性

> alt属性そのものが省略されている場合7、意味のある画像が置かれていて、しかしながら代替テキストが提供されていないものと解釈されます。この場合、スクリーンリーダーは画像の内容を可能な限り伝えようとします。title属性やその他の属性で読めるテキストが指定されていればそれを読みますが、そうでない場合、多くのスクリーンリーダーは画像のファイル名を読もうとします。ファイル名が意味ある単語ならば役に立つこともありますが、システムが生成した無意味な英数字の羅列がファイル名に使われている場合、それがそのまま読まれることになります。
> [alt属性の役割と原則](https://github.com/bakera/html-book/blob/3d1a0c2590c112abb67b77984e8a24d3ceb39475/md_text/3-7.md#alt%E5%B1%9E%E6%80%A7%E3%81%AE%E5%BD%B9%E5%89%B2%E3%81%A8%E5%8E%9F%E5%89%87)

多くの人がおそらく使用するMacOS VoiceOverやNVDAでは、ファイル名ではなく「ラベルのない画像」と読まれます。（もしかしたらファイル名を読み上げるオプションがあるかもしれないですが...）「ラベルのない画像」と読まれることに言及しておくのはどうでしょう。

いずれの指摘も、実際に読み手がスクリーンリーダーを使ったときに「本に書いてあることと違う」という感想になるのを防ぎたいという意図です。特に必要なければスルーで大丈夫です。

**Comment by momdo** [comment]
@yuyaroid `img`に`alt`属性がない場合は、ファイル名を読み上げるほうが稀という認識でよいでしょうか？
