### ISSUE TITLE
2-3 クロスオリジンの説明追加提案

### ISSUE THREAD

**Issue by ockeghem** [bakera/html-book#252]
以下の箇所について。過不足なく書かれているのですが、ここは理解できない読者が続出しそうな気がします。

> そのかわり、HTML側のJavaScriptからは、クロスオリジンで取得したサブリソースの内容を読み取ることができないようになっています。認証が必要なコンテンツは、サブリソースとしてページ上に表示することはできますが、原則としてJavaScriptから読み取ることはできないため、悪意あるサイトのオーナーに読み取られることはありません。

もう少しくどく、「悪意あるサイト上で認証が必要なコンテンツがブラウザに表示されても、その表示を見るのは本来の利用者なので問題ない。一方、JavaScriptから読み取れると、悪意あるサイトのオーナーに秘密情報が渡ってしまう」旨を書くと、少しは救えるかなと思いました。できれば図示が欲しいところです。

**Comment by bakera** [comment]
参考:
https://blog.agektmr.com/2021/11/browser-security.html

**Comment by momdo** [comment]
追加提案をいただきましたが、クロスオリジンの話はChapter1-5に移動しつつ、大幅に内容を圧縮したのでCloseとさせてもらいます。
