### ISSUE TITLE
4-4「メニューの裏側にフォーカスが当たらないようにする」の「方法3 メニュー末尾からフォーカス移動しようとした場合、メニューを自動的に閉じる」について

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#255]
4-4の方法3については、自動でメニューが閉じた時にメニューボタンにフォーカスが当たるような設計になっていたとしても、特にスクリーンリーダー(キーボード)を使い操作している場合、意図せずメニューを閉じてしまい混乱したり、ストレスを感じてしまうようなケースがそれなりにあるのではと思います。
あやまって閉じてしまう状況としては、例えばある程度ページの操作に慣れているユーザーがそれなりの速さでフォーカスを移動しているときや、始めてページを訪れた際にメニュー内の項目がわからない状態で操作したときなどです。また、閉じた時にフォーカスがメニューボタンにあったとしても、メニューの項目にアクセスする場合、メニューを展開して、項目を見つけるという操作が必要となってしまいます。

_Originally posted by @yuyaroid in https://github.com/bakera/html-book/issues/239#issuecomment-942888537_

> 確かに、フォーカスを移動しただけで意図に反して閉じるのはよろしくない場合がありそうですね。
メニューの最後の項目でTabを押した時にメニューが閉じてしまうと、Shift+tabで戻ろうとしたときにさっきの場所に戻れないとか、そういう話ですよね。

> そうですね。そういった状況での問題です。

**Comment by bakera** [comment]
本文に注意書きを追加する方向で……。

**Comment by momdo** [comment]
いい感じにまとめて記載
