### ISSUE TITLE
構成変更: a11y/ARIAの概説を先に持ってくる

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#258]
#231 
>ARIAロールとかaria-*属性の話などは先にしておかないと理解が厳しそうに感じた

>「なお、WCAG 2.1の達成基準」突然のWCAG（すでに言われていますが）

>「2021年1月時点のARIA in HTMLでは、p要素にデフォルトのARIAロールは規定されていません。」やっぱariaロールとはなにかの説明が必要そう

3章の解説にa11y/ARIAの前提知識がないと理解困難なものがある。
ARIAの説明を4-2から切り出して前に持ってくる。
a11y/WCAGの説明を行う。
場所は要検討。

**Comment by bakera** [comment]
WAI-ARIAの概説は 1-4 にいれることにした

**Comment by momdo** [comment]
- #378 

上記でひとまず取り込めているのでCloseします
