### ISSUE TITLE
構成変更: 要素説明のセクションの見出しを立ててみる

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#260]
https://github.com/bakera/html-book/issues/231#issuecomment-939683781
>>それこそsection要素的な話ですが、見出しの範囲がどこまでかがわかりにくいケースがありそう。書面になるときのスタイルでなんとかなるのかな

>これ「属性」「内容モデル」「アクセシビリティ上の注意点」みたいな見出しがあると読みやすくなりますかね?
実は原稿にはコメントで入っているのですが見出しとしては立てていないのです (いったんこうしておいて、全部書いてから考えようと思っていた)

要素解説の部分はコメントでセクションが区切ってあるが、可視の見出しとしてみてはどうか。

**Comment by bakera** [comment]
`label`要素など、要素の説明がたくさんあって説明中に小見出しを立てたい場合があり、その場合は「属性」「内容モデル」「アクセシビリティ上の注意点」などの見出しがないとどこからどこまでがどの見出しなのか分からなくなるため、見出しをおきたいです。
とはいえわりと影響大きいので要相談。

**Comment by bakera** [comment]
互換性メモ、セキュリティ上の考慮事項は別の見出しが立っていたり、単に見出しを立てるのではうまくないように見受けられる箇所が多い。一旦そのままか。

a11yと内容モデルは見出しにして問題なさそう。
ただし 3-7 ではa11yのセクションに「track要素とテキストトラック」という別の見出しが立っている箇所がある。これはそのままか。

**Comment by bakera** [comment]
見出しはありの方向で。
属性の見出しは立っていないので、手動で見出しを立てる。
3章の冒頭のほうはちゃんと見出しが立っていないことがあるので、必要に応じて立てる。

**Comment by momdo** [comment]
Chapter3について、ひととおり対応できたと思われるのでcloseします
