### ISSUE TITLE
構成変更: 仕様とは何か、を書く

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#261]
Slackより:

>「仕様」と呼んで、それはspecificationで技術文書たる仕様書のことである、というのは自明ですかね…？（HTML仕様とかHTML Standardみたいな表記のブレを統一しようとして、ふと思いました）

>仕様とは何か、の説明がいるのではないかという話ですよね。そこは本書の趣旨からして丁寧に説明した方が良いものだと思います。1-7に「仕様と実装」という見出しが立っていて

>>「仕様」(specification)は、いわば設計書にあたるものです。その設計に基づき、実際に動くものを作ることを「実装」(implementation)と呼びます。

>と書いてますが、うーん、というのと登場時期が遅い (この前にバンバン仕様という言葉を使っている) のが気になりますね。

>とすると、伊原さんが示唆したみたいに、Chapter1-7をもっと前に持ってくる感じですかね

>そうですね。1-7は「仕様を読むことの重要性」というタイトルですが、それ以前に「仕様とは」という話がもっと前に必要になるということで

**Comment by bakera** [comment]
#259 と関連

**Comment by bakera** [comment]
仕様とは何か、という話は 1-3 で扱うことにして #370 で対応。

**Comment by momdo** [comment]
#370で対応済みなのでClose
