### ISSUE TITLE
3-2: コラム：見出しランクとの併用でのアウトラインの説明

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#266]
笛田さんレビューコメントより

![image](https://user-images.githubusercontent.com/8347177/137574003-5236ec4f-18d4-4a8c-95bf-e3a04c59c884.png)

> この部分なのですが
上記は味(h2)より色(h1)の方がランクの高い見出しになるのかなと思ったのですが、味と色は同じランクの見出しになるのでしょうか？
初心者なので間違っているかもなのですが以下のようになるのかな…と思って一瞬フリーズしました(間違っているかもしれないのでその際はどこかで教えていただければ幸いです)

**Comment by bakera** [comment]
もうちょっと階層構造がはっきりわかる例の方がいいんでしょうね……パッと思いつきませんが……

**Comment by momdo** [comment]
それはそうとマークアップのコンテンツを書き直してみます
