### ISSUE TITLE
3-11：`document.write()` の使用について

### ISSUE THREAD

**Issue by ahomu** [bakera/html-book#277]
https://github.com/bakera/html-book/blob/c6034589fd8275220947939938a93e6238612b72/md_text/3-11.md#L38-L46

非推奨と言われて久しいメソッドなので、どうしてもサンプルとして使わざるを得ない場合も非推奨である旨を注釈しておきたいと思いました。

Living Standard にも圧の強い [warning](https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#document.write()) が..

**Comment by bakera** [comment]
アグリーなのですが、ul要素直下にscript要素のみ入れてli要素を入れない、というパターンの事例が他に思い付かなかったのです……。DOM操作でliを補うならscript要素は他の場所に置くほうが普通でしょうし。

**Comment by bakera** [comment]
基本そのままにして、脚注を追加する方向で……
