### ISSUE TITLE
ブラウザサポートが万全でなくても許されるなら言及ほしいかもしれないリスト

### ISSUE THREAD

**Issue by ahomu** [bakera/html-book#278]
- `loading` 属性
  -  w/ `<img>`, `<iframe>`
  - みんなだいすき Lazy Loading のネイティブ版、Safari がサポートしていないがネガティブな態度ではなさそう
- `ping` 属性
  -  w/ `<a>`, `<area>`
  - facebook がリンクを怪しく書き換えていた件で[一瞬話題](https://twitter.com/spazef0rze/status/1442377314818351109)になったような気もする

**Comment by momdo** [comment]
lazy loading…この本を書き始めたときはspecに入ってなかったから（ふるえ）

**Comment by ahomu** [comment]
用途的にもおそらくは実装的にも、ようは `navigator.sendBeacon()` なんだと思いますが、Firefox がデフォルト無効（手動でフラグ変更が必要）なのは何でなのかしら... > ping attribute

**Comment by momdo** [comment]
> Firefox がデフォルト無効（手動でフラグ変更が必要）なのは何でなのかしら... > ping attribute

951104 - Enable `<a ping>` by default https://bugzilla.mozilla.org/show_bug.cgi?id=951104
bugzillaはおそらくここでしょうけど、いまいちデフォルトで無効な理由がよくわからないですね…

あわせてよみたい：Web における技術の解釈とエコシステムによる合意形成プロセスについて | blog.jxck.io 
https://blog.jxck.io/entries/2019-04-26/hyperlink-auditing-via-ping.html

**Comment by momdo** [comment]
2つの属性のPRをマージしたのでclose
