### ISSUE TITLE
2-3: 基本認証の図版

### ISSUE THREAD

**Issue by jidaikobo-shibata** [bakera/html-book#287]
2-3の基本認証の図版ですが、暫定なだけかもしれませんが、開発環境のURLを公開するのは避けた方が良いと思います。
当たり障りのない画像を作ってみたので、差し支えなければお使いください。

https://drive.google.com/drive/folders/1y6EY6sHjrhcHg9x5_Pk9aw-Rw1CwQuq3?usp=sharing

もうちょっとほかの画像がいいということなら、用意します。

**Comment by bakera** [comment]
ありがとうございます。
図は暫定です。
(なおWG2のGitHubリポジトリでは普通にWAIC開発環境のURLを載せているので、特に秘密にはしていない認識でした)

**Comment by bakera** [comment]
なお基本認証の説明自体がなくなりました……。

**Comment by bakera** [comment]
図がなくなったのでcloseします。
