### ISSUE TITLE
仕様、仕様書、標準の言葉の揺れ

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#29]
- 仕様
- 仕様書
- 標準

の3つの言葉が揺れていると思われるので、言葉の使い方を決めておく（かあるいは、本文のどこかで説明が必要か）。

**Comment by bakera** [comment]
「仕様」はSpecification、「標準」はStandardですよね。
勧告になっていないW3C文書などは「仕様」ではあるが「標準」かどうかは怪しい場合もあるので、仕様書全般を指す時は「仕様」のほうを使うのが良いのではないかと思いました。

「HTML仕様」みたいな言い方で。

**Comment by momdo** [comment]
ひとまず仕様で統一できているはずなのでClose
