### ISSUE TITLE
Chapter未定：代表的なスクリーンリーダーについて触れる？

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#295]
derived from #231

3-1
> 「例えばiOSのVoiceOver」突然のVoiceOver

- 初出は1-2だが、これといった厚い説明がされているわけでもない
- かといってChapter4に何か詳しい説明がされているわけでもない

## 案

- Windows：ナレーター・NVDA
- iOS・macOS：VoiceOver
- Android： TalkBack

あたりに触れておく？

＃ スクリーンリーダーの動作確認ではないですが、スクリーンリーダーのラベルを付けておきます。

**Comment by bakera** [comment]
実はそれ以前に「ブラウザー」「ユーザーエージェント」もきちんと説明されていないので、合わせてどこかで説明するようにします。

**Comment by bakera** [comment]
これはいったん1-4に入れようとしています。

**Comment by momdo** [comment]
#378 で取り込めているのでCloseします。
