### ISSUE TITLE
3-3：dl要素 vs hn要素

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#342]
#231 より派生

3-3

> > dl要素を使うか見出しを使うか問題に言及があってもよさそう
> 
> 直感的に判定してしまうのでまるで言語化できる気がしないですが、少なくともそれはdlじゃないというパターンは…
> 
> - dt/ddでもって単にマークアップ的に紐付ける意図で使おうとしている
> - リストじゃないのにdl/dt/ddを使っている
> - というかそれはul/ol要素のネストでできる
>
> あたりですかね…？

という感じで使い分けのコード例をどこかに記述…？

**Comment by momdo** [comment]
多少ここでやりとりした
https://twitter.com/momdo_/status/1455365035308380165

**Comment by bakera** [comment]
dl要素のアクセシビリティのところで「dl要素のいけてない使い方」という形で書いてはどうか。
