### ISSUE TITLE
3-0? : デフォルトスタイルの話

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#351]
#231 より派生

3章全体
> デフォルトスタイルに惑わされるな、みたいな話があってもいいのかも（コラム？）

要ります？

**Comment by bakera** [comment]
入れるとしたら3-0
3章全体として見た目の話はしていないが、ブラウザーのデフォルトスタイルの存在がある、というような話を書くか?

**Comment by bakera** [comment]
3-0におよそ以下のようなことを書く:

Chapter3を通して要素の見た目の話をしている箇所があるが、これはあくまでブラウザーデフォルトスタイルの話であり、ブラウザーによって異なる場合があるし、スタイルシートで上書きも可能である。特に、ユーザースタイルシートやブラウザ、OSの設定、支援技術などによって異なるスタイルが与えられていることもあるため、注意する必要がある。

たとえば、b要素は太字を期待するが、太い文字が読めないユーザーは太字のスタイルを無効にしているかもしれないし、逆に太い字が読みやすいユーザーはすべての文字を太くしているかもしれない。

**Comment by momdo** [comment]
#444 で対応済みのためcloseします
