### ISSUE TITLE
2-4：Content modelとCategoriesの説明確認

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#387]
下記について、太田さんに確認してもらう。必要であれば太田さんにPRを出してもらう。

うーん、どうにも分かりにくさがなくなっていないような気がしていて、たぶん `p` と `mark` をそれぞれ説明した方が良いのではという気がしてきました。

mark:
 phrasingを子にできる よって markを子にできる
 自身もphrasing である よって pやmarkの子になれる

p:
 phrasingを子にできる よって  mark を子にできる
 自身はphrasing ではない よって pやmarkの子になれない

以上から、p は markを子にできるが、markはpを子にできない

というような話ですが。
まあいったんこれはこれでマージしてあとで推敲するのもありかと。

_Originally posted by @bakera in https://github.com/bakera/html-book/pull/326#pullrequestreview-787731154_

**Comment by bakera** [comment]
そもそも`p`と`mark`に特化した説明をわかりやすくする必要性があるわけでもなく、あくまで一例として流せば良いという考えに至りました。全体の流れがわかりにくいような気がしたので2-4全体を見直しています。

**Comment by bakera** [comment]
いったん対応済みということでcloseしておきます。
