### ISSUE TITLE
3章: ファイル名の連番を振り直す

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#405]
3-0や3-9-2が混乱を招くので振り直す
今振り直すとissueなどが混乱するので、DTPが終わったタイミングで振り直すことにする。

現状ずれているのも混乱していて参照が間違っていることもあるのだが、どのみちDTP側で再チェックする (`Chapter3-10(p.100)` のような参照を作る) のでDTPを経てからで良い。

**Comment by momdo** [comment]
振り直されているのでClose
