### ISSUE TITLE
言及していない要素を洗い出す

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#407]
「索引から逆引きする読者もいるので、重要でない要素についても何らかの形では触れたい」という話になった。

embed要素, data要素についてはコラム扱いで触れることにした。

他に本書で触れていない要素がないかチェックして、漏れがあれば検討する。
(とりあえずhgroupが漏れているような気がしている。3-2のコラムに唐突に要素名だけ出てくる。)

**Comment by momdo** [comment]
data要素は https://github.com/bakera/html-book/pull/373 で対応済み

**Comment by momdo** [comment]
hgroup要素、menu要素はないはず

**Comment by kiyochika** [comment]
<https://html.spec.whatwg.org/#toc-semantics>をベースにして洗い出しをしてみました。

- hgroup要素
- menu要素
- data要素
- embed要素

が取り上げられていない要素、ということであっていると思います。

したがい、hgroupとmenuをどうするか、ということになりそうですね。

個別の見出しになっていないものだと

- dt要素とdd要素（dl要素内で説明）
- figcaption要素（figure要素内で説明）
- source要素（picture要素とメディア要素内で記載あり）
- track要素（メディア要素内で説明）

がありましたが、上記の通りなので問題ないかと思います。

**Comment by bakera** [comment]
記述するというissueを作成しました (#418, #419)。
洗い出しはできたので、このissue自体は閉じて良いかなと思います。

**Comment by momdo** [comment]
要素についてひととおりコミットとして取り込んでいるのでClose
