### ISSUE TITLE
3-9：<input type=hidden>が存在しない

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#416]
https://github.com/bakera/html-book/search?q=hidden

な、なんだってー

**Comment by bakera** [comment]
ほかにtype属性に漏れがないかどうか要調査ですね。

**Comment by momdo** [comment]
他のinput typeについては不足なかったとのことです。

**Comment by momdo** [comment]
地味にセキュリティ上の注意点が記述されていますが、どう書くべきですかね…。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/hidden

**Comment by bakera** [comment]
ソースコードを見れば内容は見えるし、その気になればユーザーは書き換えできる、というようなことを書く必要がありますね。3-9を見るときに追記します。

**Comment by bakera** [comment]
>
>なお、JavaScriptから`for`属性にアクセスする場合は`htmlFor`というキーワードで参照できるようになっています。これは、`for`というキーワードが多くのプログラミング言語で予約語になっており、衝突を避けたためといわれています。

IDLの話は3-0で触れるつもりなのでこの話はそっちで説明するようにして、ここからは削除するのが良いかも。

**Comment by momdo** [comment]
対応済みのためclose
