### ISSUE TITLE
4-4: キーボードトラップについて少し説明する

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#430]
https://hack.nikkei.com/blog/advent20211204/ を読んで「キーボードトラップ」という用語に混乱があるということがわかったので。
4-4では「フォーカストラップ」「キーボードトラップ」を使い分けていますが、両者を混同するケースがあるようなので、キーボードトラップについて少し説明しておきたい。脚注でも良いかもしれない。

**Comment by momdo** [comment]
キーボードトラップを地の文でもう少し説明して（？）、WCAGの達成基準を参照するようにする

**Comment by momdo** [comment]
フォーカストラップがなんなのかも、明確になっているか確認しておく
