### ISSUE TITLE
3-3: dt要素の内容モデルを説明するか?

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#431]
#412 より:

dt要素とdd要素の個別説明がないけれど、dtの内容モデルにはやや特殊な制限がある (Flow content, but with no header, footer, sectioning content, or heading content descendants.) ので説明しておきたいような気もする。うーむ

**Comment by momdo** [comment]
詳細は仕様を参照、でどうでしょう

**Comment by bakera** [comment]
説明するとしても1行〜数行程度なんですけど、問題はdt要素そのもののエントリがないので内容モデルを説明する場所がない、ということですね。

**Comment by momdo** [comment]
内容モデルを追記するならば、見出し「dl要素」を「dl要素、dt要素、dd要素」にする感じですかね。

**Comment by momdo** [comment]
マージ済みなのでClose
