### ISSUE TITLE
カッコ書きを含むWCAG達成基準の名称が分かりにくい

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#438]
#191 でWCAG達成基準を日本語で表記することにしていて、それは良いのですが、実際書いてみるとどこまでが名称なのか分かりにくいケースがあります。たとえば以下のような文です。

>WCAG 2.1達成基準2.4.4リンクの目的 (コンテキスト内)[^21]では、このようなリンク先が理解できないリンクを避け、どのようなリンク先であるのかが理解できるようにすることを求めています。

「リンクの目的 (コンテキスト内)」というのが名前なのですが、カッコ部分が達成基準の名前なのか地の文なのかがわかりにくくなっています。たとえば達成基準の名称をカギ括弧で括るなど、何らか工夫をした方が良いように思いました。

>WCAG 2.1達成基準2.4.4「リンクの目的 (コンテキスト内)」[^21]では、

**Comment by momdo** [comment]
基本的に達成基準をかぎ括弧でくくるようにしたので解決しているはず。
