### ISSUE TITLE
「このCahpter」という表現でセクションを指さないようにする

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#449]
>Chapterは章という意味なので、このChapterではという表現だと、Chapter1全体を指すことになります。Chapter1-1だけを指すのであれば「このセクション」という表現になりますが、デザインフォーマットではセクションという表現を使っていないので、ここでは、としています。

「このCahpter」というような表現を確認し、セクションを指している場合は何らか改める。

**Comment by momdo** [comment]
v5で、Chapter4-3の1箇所に赤字を入れたのでClose
