### ISSUE TITLE
スタイルを当てたい表示例を洗い出す

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#481]
コードの表示例の中には、ブラウザーデフォルトスタイルでは分かりにくいものもあるのでそれを洗い出す。

**Comment by bakera** [comment]
今のところ、

Chapter3-2 〓14〓 (「13. article要素を入れ子にした記述例」の表示例)
Chapter3-2 〓18〓 (「17.nav要素の直下にul要素を入れた記述例」の表示例)
Chapter3-8 〓05〓 (「4. 列見出し」の表示例)

**Comment by momdo** [comment]
「13. article要素を入れ子にした記述例」の表示例はママですが、ほかについては調整したのでClose
