### ISSUE TITLE
要素名・属性名の大文字小文字の区別の話が抜けていたかもしれない

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#486]
data-*属性を見ていて気づきましたが、
「HTML構文では要素名・属性名の大文字小文字を区別しない、構文解析時に小文字に変換される」
という話って書いてましたっけ?
あまりにも基本的すぎて逆に見落としていたのではという気がしており、Chapter2の要素・属性のところに入れ込む必要があるかもしれません。

**Comment by bakera** [comment]
なお、2-1ではDOCTYPEについて、2-2では列挙型属性のキーワードについて大文字小文字を区別しない旨が書かれています。
要素名、属性名についてはなにもないような……

**Comment by momdo** [comment]
要素名・属性名：2-2に記述する感じで
数行を書いてみる（後回し）

**Comment by momdo** [comment]
それぞれ、2-1と2-2にMEMOとして、以下を挿入するのでどうか

＜MEMO＞
要素名は大文字小文字を区別しません。

＜MEMO＞
属性名は大文字小文字を区別しません。属性値の大文字小文字の区別は、属性によって異なります。

**Comment by bakera** [comment]
ありがとうございます。
盛り込みたい情報としては以下のようなところで、

- HTML構文では、大文字小文字は区別しない
- (HTML構文では)大文字で書くと小文字として解釈される
- XML構文では、大文字小文字を区別する

2-1だと、現状こうなっているところを、
```
<本文>
h1 と書かれた部分は「タグ名（tag name）」といい、要素の名前である「要素名 element name 」を表しています。
```

こうするとか。

```
<本文>
h1 と書かれた部分は「タグ名（tag name）」といい、要素の名前である「要素名 element name 」を表しています。HTML構文ではタグ名の大文字小文字を区別せず、大文字で書いた場合は小文字に変換されて解釈されます。

<memo>
XML構文の場合、大文字小文字を区別しません。HTMLの要素名は小文字で定義されており、大文字で記述すると別の要素とみなされます。
```

レイアウト的に文が本文に入らなければ、memoに全部入れるでも良いと思いますが。

**Comment by bakera** [comment]
2-2のほうはいろいろ微妙ですね……。
(属性値が省略される場合なども考慮すると微妙な感じがする)

```
＜本文＞
属性を書くときは、属性名の後ろに=（U+003D、等号）を記述し、続けて属性値を書きます。属性値は、原則として"（U+0022、二重引用符）または'（U+0027、単一引用符）で括ります。引用符はどちらを使っても構いませんが、同じ引用符を用いてペアにしなければなりません。
```


```
＜本文＞
属性を書くときは、まず属性名を記述します。HTML構文では属性名の大文字小文字を区別せず、大文字で書いた場合は小文字に変換されて解釈されます。
属性値を記述する際は、属性名の後ろに=（U+003D、等号）を記述し、続けて属性値を書きます。属性値は、原則として"（U+0022、二重引用符）または'（U+0027、単一引用符）で括ります。引用符はどちらを使っても構いませんが、同じ引用符を用いてペアにしなければなりません。

<memo>
XML構文の場合、大文字小文字を区別しません。HTMLの属性名は小文字で定義されており、大文字で記述すると別の属性とみなされます。
```

**Comment by momdo** [comment]
本文に突っ込むのは苦しいと思いますね…あと別にXML構文についてそこまで厚くする必要もない（というかHTML構文ではという前書きをすれば、XML構文の場合は異なることが暗にわかる）かと…？
ということでそれぞれ以下でいかがでしょう…？
（あんまりわかってないですが、要素名ではなく、タグ名でよいです？）


＜memo＞
HTML構文では、タグ名の大文字小文字を区別しません。タグ名は小文字で定義されており、大文字は小文字に変換して解釈されます。

＜memo＞
HTML構文では、属性名の大文字小文字を区別しません。属性名は小文字で定義されており、大文字は小文字に変換して解釈されます。属性値の大文字小文字の区別は、属性によって異なります。

**Comment by bakera** [comment]
パーサー的に大文字の小文字変換をやっているのは "13.2.5.8 Tag name state" のところで、Tag nameなので「タグ名」で良いかと思います。

https://html.spec.whatwg.org/multipage/parsing.html#tag-name-state
>ASCII upper alpha
>Append the lowercase version of the current input character (add 0x0020 to the character's code point) to the current tag token's tag name.

ちなみに属性はこっちで attribute name です。

https://html.spec.whatwg.org/multipage/parsing.html#attribute-name-state
>ASCII upper alpha
>Append the lowercase version of the current input character (add 0x0020 to the character's code point) to the current attribute's name.

**Comment by momdo** [comment]
よいと思います。これで赤字を入れておきますね。。

**Comment by momdo** [comment]
対応済みなのでClose
