### ISSUE TITLE
MDNのデザインリニューアルによる影響を確認する

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#490]
どうもMDNの見た目が変わったぽいので、影響の有無を確認しておきたい。
とりあえず、MDNのnav要素の用例についてはスクショの差し替えが必要になる可能性があります。
https://github.com/bakera/html-book/pull/466#issuecomment-1034523035

**Comment by momdo** [comment]
んーそこまで変わってますかね？致命的かというとそうでもないような。

**Comment by momdo** [comment]
影響ないはずなのでClose
