### ISSUE TITLE
側注でURLを参照する際のリンク先の見出しの扱いをどうするか

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#493]
いまさらの話ですが、側注でURLを参照する際、URLの前に何を書くのかが揺れているように思います。
特に、リンクがフラグメントを含む場合、

- 何も書かない
- リンク先のページの見出し
- リンク先のセクションの見出し
- リンク先のページの見出し + セクションの見出し

の4パターンくらいあるような気がしています。
リンク先のセクションの見出しだけが書いてある場合、以下のような感じになって微妙にわかりにくいことがあります。

>Specificity
>https://www.w3.org/TR/css-cascade/#cascade-specificity

統一しなくても良いという考えもありえるでしょうが、方針を確認しておきたいです。

**Comment by momdo** [comment]
See also https://github.com/bakera/html-book/issues/165

統一するの難しくないですか（統一した方がよいのはそれはそう）

あと、URLの前に「～はxxの…を参照してください」とあったりなかったりするので、
これがさらにパターンの複雑さを加速させているとかなんとか。

**Comment by bakera** [comment]
統一しない、と決めるならそれはそれで良いかと。

ちなみに側注が本文のどこに対応するか分かりにくい場合が結構あって、そういうときにURLの前に文を補っていることがあります。
