### ISSUE TITLE
カバー背景のテキストを作る

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#498]
カバー背景のHTMLや単語のテキストを用意する

**Comment by bakera** [comment]
左側のHTMLですが、現在の書影では2-1の「開始タグの省略」のところに出てくる以下のコード例が使われています。

```
<!DOCTYPE html>
<html>
  <head>
    <title>test</title>
  </head>
  <body>
    <table>
      <tbody>
        <tr>
          <th>見出し1</th>
          <td>データ1</td>
        </tr>
        <tr>
          <th>見出し2</th>
          <td>データ2</td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
```

本書内で使用している他のコード例を見ると、DOCTYPEから書いているものは意外と少なく、同じく2-1の末尾にある以下のコード(最低限のHTML)くらいです。

```
<!DOCTYPE html>
<html>
  <head>
    <title>最低限のHTML</title>
  </head>
  <body>
    <h1>最低限のHTML</h1>
    <p>これはHTML文書です！</p>
  </body>
</html>
```

**Comment by bakera** [comment]
単語の方、とりあえず用語を抽出して取捨選択したりしてみた
https://docs.google.com/spreadsheets/d/1MXeMR8Qyu0S7AsyAGZQyiyvXBsUpcn6p9e5Haqqvzyc/edit?usp=sharing

**Comment by bakera** [comment]
カバー背景の用語は現状30個。40個くらい挙げておいて末尾を切ってもらうのが良いか。

**Comment by bakera** [comment]
HTMLコード例、本書の目次をマークアップしたものを載せてはどうだろうか?

**Comment by bakera** [comment]
HTMLコード例、これでいかが?
https://github.com/bakera/html-book/blob/master/text/cover/code-sample.html

**Comment by momdo** [comment]
基本的によいと思いますが、インデントの調整だけしておくとよいかと？

**Comment by bakera** [comment]
インデントはデザイン側の都合でいい感じにしてもらえればと思っていました。

**Comment by momdo** [comment]
表紙に取り込まれているのでClose
