### ISSUE TITLE
willful violationの訳語が揺れている

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#502]
用語抽出で気づきましたが力強く揺れていました。

1-7
>そのような意図的な違反は、「故意の違反（willful violation）」として明示しています。

3-9
>これは「意図的な逸脱（willful violation）」です。

PDFでどうなっているか確認して、必要に応じて統一。
「意図的な逸脱」のほうがいい?

**Comment by momdo** [comment]
辞書に寄せるなら前者、意図を汲むなら後者ってところですかね。

**Comment by momdo** [comment]
意図的な逸脱で統一で赤入れ済み。
