### ISSUE TITLE
form要素のautocomplete属性の説明を調整する

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#503]
form要素のautocomplete属性については以下のようになっている。

>form要素にはフォーム送信の制御に関する属性がいくつかあります。また、下記の他にautocomplete属性を指定できます。autocomplete属性については、後述のフォームコントロールの共通属性（P233）を参照してください。

しかし実際にはform要素のautocomplete属性はinput要素のautocomplete属性とは異なり、on/offしか指定できない。
autocomplete属性の説明のところに「form要素のautocomplete属性はon/offしか指定できない」というようなことを書くべきか。

**Comment by bakera** [comment]
autocomplete属性の説明には以下のような箇所があるので、ここを調整する。

>この属性はform要素にも指定でき、その場合はフォーム内のコントロールのデフォルトの挙動を指定します。個々のフォームコントロールにautocomplete属性が指定されている場合、個々のコントロールに指定された属性が優先されます。

**Comment by momdo** [comment]
調整反映済みなのでClose
