### ISSUE TITLE
p.32 WORDの誤り

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#526]
ご指摘ツイート：
https://twitter.com/sarasvati635/status/1517636857064194048

> HTML解体新書のp32の備考欄でICANNがICAANって書いてある

誤：ICAAN（Internet Corporation for Assigned Names and Numbers）
↓
正：ICANN（Internet Corporation for Assigned Names and Numbers）

**Comment by bakera** [comment]
2刷では修正済み
