### ISSUE TITLE
p.97、p.210 CHAPTERがキャメルケースになっている

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#532]
#531 の派生

CHAPTERとすべきところがChapterになっている

p.97 アクセシビリティ上の注意点

> アクセシビリティツリーについてはChapter1-2を参照してください。

> アクセシブルな名前についてはChapter4-2を参照してください。

p.210 dialog

> 使用例はChapter3-12のdialog要素を参照してください。

**Comment by momdo** [comment]
ご指摘ツイートもあり
https://twitter.com/sarasvati635/status/1518023052080349184

> p210のdialogの説明で他では「CHAPTER 3-6」のように書かれている参照が「Chapter3-12」と書かれている

**Comment by bakera** [comment]
p050に"Chqpter1-5"という表現あり。

**Comment by bakera** [comment]
p97 2刷反映済み
p210 2刷反映済み
p50 2刷反映済み
