### ISSUE TITLE
p.5、p93 「エンベディッドコンテンツ」の誤り

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#533]
ご指摘のツイート：
https://twitter.com/sarasvati635/status/1517838687773806592

> p005、CHAPTER3-08のタイトルが「エンベディッドコンテンツ」であるべきところ「エンベティッドコンテンツ」になってる（実際のp182のタイトルは「エンベディッドコンテンツ」）

指摘のp.5の目次と、p.93の中扉が誤っている

誤：エンベティッドコンテンツ
↓
正：エンベディッドコンテンツ

**Comment by momdo** [comment]
#507 とdupeだがとりあえずイキで

**Comment by bakera** [comment]
索引にエンベデッドがあるのでこちらも修正

**Comment by bakera** [comment]
2刷修正済み。
dupe なのでとじておきます。
