### ISSUE TITLE
p.226 button要素の参照の誤り

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#549]
ご指摘のツイート：
https://twitter.com/kyo_ago/status/1525639630523355142

見出し「ボタン：submit、reset、button」でのページ参照に誤りがある。

誤：CHAPTER 3-10のbutton要素（P212）を参照してください。
↓
正：CHAPTER 3-11のbutton要素（P238）を参照してください。

**Comment by bakera** [comment]
2刷未反映
