### ISSUE TITLE
p.20 コラム内の誤植

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#552]
ご指摘ツイート
https://twitter.com/girigiribauer/status/1527619793754664960?s=20&t=E_X4B47VSATr0KQYeNh4IA

文字が入れ替わっている

誤：APRAネット（Advanced Research Projects Agency Network）は
↓
正：ARPAネット（Advanced Research Projects Agency Network）は

**Comment by bakera** [comment]
2刷未反映
