### ISSUE TITLE
p105. 旧式だが適合する機能(Obsolete but conforming) が鉤括弧なし英語併記になっている

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#562]
p105.のmemoには以下のようにある。

>`type`属性は廃止されていますが、値が`"text/css"`の場合(大文字小文字は区別しません)のみ、旧式だが適合する機能(Obsolete but conforming)として仕様に適合します。

#483 では「旧式だが適合する機能(Obsolete but conforming)」を初出時のみ鉤括弧あり英語併記、それ以降は鉤括弧なし英語併記なしとすることにしている。ここではおそらく英語を削除するのが正しい。以下のようになる。

>`type`属性は廃止されていますが、値が`"text/css"`の場合(大文字小文字は区別しません)のみ、旧式だが適合する機能として仕様に適合します。

**Comment by bakera** [comment]
なお「旧式だが適合する機能(obsolete but conforming)」の初出はp045で、ここは鉤括弧あり英語併記になっている (正しい)

>現在の仕様で廃止された機能の中には、互換性のためにブラウザーの 挙動が定義されているものもあり、「旧式だが適合する機能(obsolete but conforming)」として規定されています。

**Comment by bakera** [comment]
p221, p272には英語併記なし鉤括弧ありが残っていて、#483 が全然徹底できてないじゃん感があり……

**Comment by momdo** [comment]
頑張って直そうとはしてたんですよ…
