### ISSUE TITLE
コラムの挿入位置

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#588]
たとえば、p.297「コラム：ネイティブ、暗黙、ホスト言語」は、
アウトラインをぶった切る形になるが、位置としてここでよいか。

マークアップで何らか調整するのか…？（`<figure>`とか）

**Comment by bakera** [comment]
マークアップ上はコラムは section 要素にしてあります。
figureとかasideの類ではないような……

紙版のレイアウト都合に縛られる必要はないので、挿入位置の調整でいい感じになるなら位置を変えてしまうのが良いと思います。

**Comment by bakera** [comment]
コラムの見出しレベルを調整すれば良いのでは

**Comment by bakera** [comment]
挿入位置が間違っているというわけでもなく、単に上位の見出しよりもレベルの高い見出しにするとおかしくなるという話だと思うので、見出しレベルを調整しました。
