### ISSUE TITLE
p131コラム 「定義」かぶり

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#593]
軽微な話ですが、

>現在のHTML仕様では意味が再定義され、ユーザーが操作可能なボタンやリンクなどを列挙するツールバー、メニューバーなどを表すものと定義されています。

「再定義され……と定義されています」と定義がかぶっているので、文末は「とされています」でよいかと思われます。

**Comment by momdo** [comment]
> \[\^12]: リストマーカーの種類はCSSの`list-style-type`プロパティによる指定が優先されます。

についても修正されていますが、こちらもトリですか？

**Comment by momdo** [comment]
ああこれは、#592 の話ですね…
