### ISSUE TITLE
3-4 a要素の説明

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#61]
`href`属性を持たない場合の話をする？

**Comment by momdo** [comment]
`href`属性を持たない場合の話は特に思い浮かばないのでしないが、HTML4で言うところのブロック要素を`a`要素で囲む話は追記する方向で。

**Comment by jidaikobo-shibata** [comment]
（全部無視してもらって構いません。）
すこしお話はしましたが、ちょうレガシーな世界では `name` や `id` のみ持っていた時代がそれなりに長く会ったことと、 `href` 属性を持たないで `onclick` `onkeypress` だけを与えていた事例、 `href` があっても、 `#` や `javascript:void(0)` だけ入っていたこと、 `href` 属性がないと、 `tabindex=1` 状態になること、などが思い出されました。

**Comment by momdo** [comment]
@jidaikobo-shibata 

コメントありがとうございます。
というわけで、いろいろ盛ったPRを作ってみましたが、いかがでしょうか。

**Comment by jidaikobo-shibata** [comment]
ご勘案感謝します！
