### ISSUE TITLE
p207 `col`要素が列グループを指定?

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#631]
p207に以下のようにある。

>`colgroup`要素に`span`属性を指定しない場合、子要素となっている`col`要素が列グループを指定できます。

「`col`要素が列グループを指定」という表現はおかしいのではないか。列グループを指定するのはあくまで`colgroup`要素。ここで言っているのは、その子要素の`col`要素の数によってその列グループに所属する列が決まるという話。
丁寧に

子要素となっている`col`要素によって、その列グループに所属する列を指定できます。

という程度にできるとよいか。

**Comment by bakera** [comment]
すぐ下のコード例17のキャプション「`col`要素が列グループを指定」も要調整。

**Comment by momdo** [comment]
> すぐ下のコード例17のキャプション「col要素が列グループを指定」も要調整。

col要素が列グループに所属する列を指定

とかでしょうか？
