### ISSUE TITLE
p224 側注のMDNリンク切れ

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#637]
p224の側注に以下のURLの記載がある

https://developer.mozilla.org/ja/docs/Web/API/File/Using_files_from_web_applications

これはリンク切れである。以下のURLが正しいと思われる。

https://developer.mozilla.org/ja/docs/Web/API/File_API/Using_files_from_web_applications

File→File_APIの修正が必要。
(元々間違っていたのか、MDNの側でURLが変わったのかは謎)

**Comment by bakera** [comment]
ページタイトルもWebアプリケーション→ウェブアプリケーションとするべきか

**Comment by bakera** [comment]
以下のようになる

MDNのウェブアプリケーションからのファイルの使用が参考になります。
<https://developer.mozilla.org/ja/docs/Web/API/File_API/Using_files_from_web_applicationss>

**Comment by momdo** [comment]
@bakera 

URL、最後の「s」が衍字になってますね…正確にはこうかと。
https://developer.mozilla.org/ja/docs/Web/API/File_API/Using_files_from_web_applications
