### ISSUE TITLE
p270 「type=moduleを不明な属性として無視」は不正確

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#659]
p270の`nomodule`属性に以下のような記述がある。

>一方、モジュールをサポートしないブラウザーは`type=module`を不明な属性として無視するため、モジュールスクリプトは無視されます。

この記述はやや不正確で、正確にいうとtype属性が不明な属性なわけではない。
type属性は昔からあるが、moduleという属性値が不明なMIMEタイプなので無視されるというのが適切。

不明な属性→不明な属性値、もしくは不明な指定、とするくらいでよいか。

**Comment by bakera** [comment]
さらに正確を期すならtype=moduleの指定を無視するわけではなく、不明なtypeとして正しく扱った結果としてそのscript要素を無視するので、もう少し調整した方が良いか。こんな感じ?

一方、モジュールをサポートしないブラウザーはtype=moduleの指定されたscript要素を処理しないため、モジュールスクリプトは無視されます。

**Comment by momdo** [comment]
> type=moduleが指定されたscript要素を処理しないため、

理由が理由になっていない気もしており、

> 不明な属性→不明な属性値

がよいのかなと思いますが、いかがでしょうか。
