### ISSUE TITLE
p59 属性値に引用符を含める場合の説明が不適切

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#669]
p59にて、属性値に引用符を含める場合の説明として以下のようにある。

> なお、属性値に引用符を含める場合、 04 のように記述します。

04はこうなっている。

```
<span title="Murphy's law">Anything that can possibly go wrong, does.</span>
```

これはたまたま属性値の引用符と値の引用符の種類が違うためこう書けているだけであり、なんの説明にもなっていない (属性値に引用符を含める場合、通常は文字参照を使用する)。

前の原稿を確認すると、この箇所は以下のような文になっていた。

>属性値に引用符を含めたい場合、属性名を括る引用符のペアと異なる引用符については、そのまま書くことができます。

この文であれば妥当である。わかりにくいということで変えたのかもしれないが、変えた後の現状の記述はほぼ誤りと言ってよく、戻した方がまだ良いように思われる。

以下のようにするか?

属性値に引用符が含まれている場合、属性名を括る引用符のペアと異なる引用符であれば、そのまま書くことができます。

**Comment by bakera** [comment]
文字参照については2-6に記載があり、p80に属性値内に引用符を書く方法が出てくるので、そちらを参照するか、あるいはここからはいっそ完全に削除してしまうのもあり。

**Comment by momdo** [comment]
p89を参照している注があるので、ここにp80への参照を付け足すのはありかと。

> あるいはここからはいっそ完全に削除してしまうのもあり。

削除してしまってよいと思います。

**Comment by bakera** [comment]
これどうするかな
削除すると図版番号が全部ズレるので影響が大きいように思われ。

**Comment by bakera** [comment]
これを

>なお、属性値に引用符を含める場合、 04 のように記述します。
> 04 単一引用符がある属性値を二重引用符で括った記述した例
>`<span title="Murphy's law">Anything that can possibly go wrong, does.</span>`

こうするか

>なお 04 のように、属性値の引用符と異なる引用符はそのまま記述できます。
> 04 単一引用符がある属性値を二重引用符で括って記述した例
>`<span title="Murphy's law">Anything that can possibly go wrong, does.</span>`
