### ISSUE TITLE
p297 コラムの文章表現が不適切

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#681]
p297のコラムに以下の文がある。

>WAI-ARIA 仕様では、ネイティブ(native)、暗黙の(implicit)、ホス ト言語(host language)といった用語が出てきますが、これらはすべ て同じ概念を表しているものです。つまり、HTML を考える場合、す べて HTML デフォルトの(default)と読み替えることができます。

ネイティブ(native)、暗黙の(implicit)、ホスト言語(host language)という言葉自体が同じ概念というわけではない。
あくまでロールの話であり、正確に書くとこうなる。

WAI-ARIA 仕様では、ネイティブの(native)ロール、暗黙の(implicit)ロール、ホスト言語の(host language)ロール、といった表現が出てきますが、これらはすべて同じ概念を表しているものです。つまり、HTML を考える場合、すべて HTML デフォルトの(default)ロールと読み替えることができます。

冗長な感じもするが、ロールと言わないと逆にわかりにくく、続く文章 (「この文脈でのセマンティクスは、ロールだけでなく…」) とのつながりも不明になっているので、ちゃんと書いた方がよいように思う。

**Comment by momdo** [comment]
https://html.spec.whatwg.org/multipage/dom.html#wai-aria

> The "default semantics" referred to here are sometimes also called "native", "implicit", or "host language" semantics in ARIA. \[ARIA\]

（もともとがいい加減なのでアレですが）ロールだったりセマンティクスだったりするとおもわれるので、ロールに絞っても…という感じは。

**Comment by bakera** [comment]
あー原文は "native", "implicit", or "host language" semantics なんですね。role ではなく semantics が落ちていたのか。
ちゃんと書くとこうですかね。

WAI-ARIA 仕様では、ネイティブ(native)セマンティクス、暗黙の(implicit)セマンティクス、ホスト言語の(host language)セマンティクスといった用語が出てきますが、これらはすべて同じ概念を表しているものです。つまり、HTML を考える場合、す べて HTML デフォルトの(default)セマンティクスと読み替えることができます。

**Comment by momdo** [comment]
よいと思います！
