### ISSUE TITLE
p300 「その要素」が何を指すのか曖昧な文

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#683]
p300 に以下の文がある。

>要素が必須の所有要素を持つ場合、その要素のロールだけを変更すると、 矛盾が生じます。

この文の「その要素」が親要素(文中最初に登場する「要素」)と子要素(「必須の所有要素」)のどちらを指すのかが不明である。実際には親要素を指すので「その要素の」→「親要素の」とするとよいか。

**Comment by momdo** [comment]
> 親要素の要素のロールだけを変更すると、 矛盾が生じます。

ここだけ見ると、子要素を明示的にロールを書き換える必要がある、ように見えますね…（実際にはあとで説明されていますが）。
