### ISSUE TITLE
p.14 chapter1-2 注釈2の文章がおかしい

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#696]
>仕様の要求を実現することを「実装(implementation)」といいます。ブラウザーの場合、アプリケーションのプログラムを実際に書いて、動作することが実装にあたります。動作する行為だけでなく、動作するように作られた成果物のことも「実装」といい、「実装が存在する」「仕様と実装が食い違う」などといいます。

「動作すること」「動作する行為」というのはおかしい。「動作させること」「動作させる行為」ではないか。

**Comment by bakera** [comment]
これを:

>仕様の要求を実現することを「実装(implementation)」といいます。ブラウザーの場合、アプリケーションのプログラムを実際に書いて、動作することが実装にあたります。動作する行為だけでなく、動作するように作られた成果物のことも「実装」といい、「実装が存在する」「仕様と実装が食い違う」などといいます。

こうする:

仕様の要求を実現することを「実装(implementation)」といいます。ブラウザーの場合、アプリケーションのプログラムを実際に書いて、動作させることが実装にあたります。動作させる行為だけでなく、動作するように作られた成果物のことも「実装」といい、「実装が存在する」「仕様と実装が食い違う」などといいます。

**Comment by momdo** [comment]
こちらは紙版でも対応が必要のはず。

p.14の2つ目の注釈になります。

**Comment by bakera** [comment]
#764 で対応
