### ISSUE TITLE
1-7 「警告を必ずしもゼロにすることに固執する必要はありません」日本語として変?

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#705]
1-7 「チェックツールを使用する」の部分

>警告を必ずしもゼロにすることに固執する必要はありません。

日本語としてややおかしい感があり。以下のいずれかが望ましいと思われます。

- 警告をゼロにすることに固執する必要はありません。
- 警告を必ずしもゼロにする必要はありません。

**Comment by momdo** [comment]
前者がよさそうです。

**Comment by bakera** [comment]
p049のさいごのほう、

>警告を必ずしもゼロにすることに固執する必要はありません。

「必ずしも」をトリ、以下のようにする。

警告をゼロにすることに固執する必要はありません。

**Comment by bakera** [comment]
#760 で対応
