### ISSUE TITLE
3-6 注釈12 文言を調整したい

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#718]
```
[^12]: スキップリンクは必須ではありません。スキップリンクを設けなくても、メインコンテンツの位置に見出しを配置したりする、メインコンテンツを`main`要素としてマークアップするといった方法を用いることで、WCAG 2.1達成基準2.4.1の要件を満たすことができます。
```

配置したりする → 配置する
文全体として「……といった方法」と言っているので「したり」は不要と思われます。

**Comment by bakera** [comment]
p164 の最初の注釈

>スキップリンクは必須ではありま せん。スキップリンクを設けなく ても、メインコンテンツの位置に 見出しを配置したりする、メイン コンテンツを main 要素としてマー クアップするといった方法を用い ることで、WCAG 2.1達成基準 2.4.1 の要件を満たすことができま す。

「配置したりする」→ 「配置する」とする。以下のようになる。

スキップリンクは必須ではありません。スキップリンクを設けなくても、メインコンテンツの位置に見出しを配置する、メイン コンテンツを main 要素としてマー クアップするといった方法を用いることで、WCAG 2.1達成基準 2.4.1 の要件を満たすことができます。

**Comment by momdo** [comment]
@bakera 

配置したり、…用いるというのもありかと…？

スキップリンクは必須ではありません。スキップリンクを設けなくても、メインコンテンツの位置に見出しを配置したり、メイン コンテンツを main 要素としてマー クアップするといった方法を用いることで、WCAG 2.1達成基準 2.4.1 の要件を満たすことができます。

**Comment by bakera** [comment]
この辺は好みの問題になってきますが、個人的には「たり」を使うなら後半も「たり」にしたい派です。
こんな感じだとどうですかね?

スキップリンクは必須ではありません。スキップリンクを設けなくても、メインコンテンツの位置に見出しを配置したり、メイン コンテンツを main 要素としてマー クアップしたりすることで、WCAG 2.1達成基準 2.4.1 の要件を満たすことができます。

**Comment by momdo** [comment]
> 個人的には「たり」を使うなら後半も「たり」にしたい派です。

よいと思います。そうしましょう。

**Comment by bakera** [comment]
p164 の最初の注釈

>スキップリンクは必須ではありません。スキップリンクを設けなくても、メインコンテンツの位置に見出しを配置したりする、メインコンテンツを main 要素としてマークアップするといった方法を用いることで、WCAG 2.1達成基準 2.4.1 の要件を満たすことができます。

これを以下のようにする。

スキップリンクは必須ではありません。スキップリンクを設けなくても、メインコンテンツの位置に見出しを配置したり、メインコンテンツを main 要素としてマークアップしたりすることで、WCAG 2.1達成基準 2.4.1 の要件を満たすことができます。

**Comment by bakera** [comment]
#756 で対応。
