### ISSUE TITLE
p174 3-6 注43 誤記 ucg→ugc

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#719]
3-6 注43 

```
[^43]: Googleは`nofollow`をさらに細分化したキーワード`sponsored`や`ucg`をサポートしています。\
<https://developers.google.com/search/docs/advanced/appearance/qualify-outbound-links?hl=ja>
```

ucg → ugc が正しい (user generated contents)

**Comment by momdo** [comment]
紙版でも綴りが誤っている

p174 2つ目の注釈は

誤：
> ucg

正：
ugc

**Comment by bakera** [comment]
リンクが切れてますね……

**Comment by bakera** [comment]
いまのURLはこれか
https://developers.google.com/search/docs/crawling-indexing/qualify-outbound-links?hl=ja

**Comment by bakera** [comment]
EPUB版ではしれっとURLを直してしまうか?

**Comment by bakera** [comment]
#755 で対応。リンクも修正してしまいました。
