### ISSUE TITLE
3-8 地図の話で「地の文」という表現を使うと紛らわしい

### ISSUE THREAD

**Issue by bakera** [bakera/html-book#720]
3-8 「代替テキストの第 2 原則:繰り返しを避ける」の箇所に以下のようなくだりがある。

>もう 1 つの原則は、繰り返しを避けることです。画像の前後にキャプションや説明文を提供することがしばしばありますが、その情報を繰り返 すべきではありません。 07 は、 06 と同じ地図を想定していますが、ここ では地図の下に道順の説明文が付いています。
>地の文で道順を示しているため、alt 属性には道順を記載せず、単にど のような画像かを記しています。冗長な情報を省くことで、スクリーン リーダーが同じ内容を二度読み上げることを防ぎます。

地図の話をしているため、「地の文」という表現が「地図の文」と読めてしまうなど紛らわしくて混乱することがあるようだった。「本文」など別の表現にしてもよいのかもしれない。

**Comment by bakera** [comment]
単に「地の文」→「本文」でよいのではなないか。
p186のこれを

>地の文で道順を示しているため、alt 属性には道順を記載せず、単にどのような画像かを記しています。冗長な情報を省くことで、スクリーン リーダーが同じ内容を二度読み上げることを防ぎます。

こうする。

本文で道順を示しているため、alt 属性には道順を記載せず、単にどのような画像かを記しています。冗長な情報を省くことで、スクリーン リーダーが同じ内容を二度読み上げることを防ぎます。

p198にも

>テーブルの説明を提供したい場合は、地の文や caption 要素などで提供 します。

があるが、こちらも本文でよいかもしれない。

**Comment by momdo** [comment]
@bakera 
p186の07のキャプションも合わせて「地の文」→「本文」にする必要があるかと

> 07 地の文で道順を解説した場合の代替テキストの例

こうする。

07 本文で道順を解説した場合の代替テキストの例

**Comment by bakera** [comment]
ありがとうございます! まとめるとこうですね。

p186で2箇所

>地の文で道順を示しているため、alt 属性には道順を記載せず、単にどのような画像かを記しています。冗長な情報を省くことで、スクリーン リーダーが同じ内容を二度読み上げることを防ぎます。
→
本文で道順を示しているため、alt 属性には道順を記載せず、単にどのような画像かを記しています。冗長な情報を省くことで、スクリーン リーダーが同じ内容を二度読み上げることを防ぎます。

>07 地の文で道順を解説した場合の代替テキストの例
→
07 本文で道順を解説した場合の代替テキストの例


p198で1箇所

>テーブルの説明を提供したい場合は、地の文や caption 要素などで提供します。
→
テーブルの説明を提供したい場合は、本文や caption 要素などで提供します。

**Comment by bakera** [comment]
#754 で対応
