### ISSUE TITLE
4-1 グローバル属性

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#74]
グローバル属性で何を書くべきか？を整理します。

評価：○いる　△いるかも　×いらない　★現時点で書いてる

- accesskey△
- autocapitalize×
- autofocus×
- contenteditable△
- dir×
- draggable×
- enterkeyhint×
- hidden△
- inputmode×
- is×
- itemid×
- itemprop×
- itemref×
- itemscope×
- itemtype×
- lang○★
- nonce×
- spellcheck×
- style○★
- tabindex△
- title○★
- translate×

- class○
- id○
- slot×

- ARIA roleおよびaria-*属性△

- 特定のイベントハンドラーコンテンツ属性（onabortなどon*属性）○

- カスタムデータ属性（data-*）○★

- xmlns×
- xml:space×

**Comment by bakera** [comment]
HTML Spec.の目次に見出しが立っているものは説明しておきたいような。

3.2.6.1 The title attribute
3.2.6.2 The lang and xml:lang attributes
3.2.6.3 The translate attribute
3.2.6.4 The dir attribute
3.2.6.5 The style attribute
3.2.6.6 Embedding custom non-visible data with the data-* attributes

これでいくと dir と translate は説明した方がよさそう?

**Comment by momdo** [comment]
@bakera まあそれでいうと

2.6.6 Nonce attributes
6.1 The hidden attribute
6.4.3 The tabindex attribute
6.4.7 The autofocus attribute
6.5.2 The accesskey attribute
6.6.7 Input modalities: the inputmode attribute
6.7.7 The draggable attribute

とか3章ではないところだけど単独で立っているものはそこそこあるんですよね…
