### ISSUE TITLE
`a` vs `button`要素

### ISSUE THREAD

**Issue by momdo** [bakera/html-book#75]
- ニーズがあるっぽい
- しかし、本書前半（知識編的な位置付け）で扱うには厳しい？
    - 扱うなら実践的な？

**Comment by kazuhito-kidachi** [comment]
最近、まさにそんな感じの記事を立て続けに目にしました。
https://michaelspellacy.com/pushing-buttons/
https://css-tricks.com/a-complete-guide-to-links-and-buttons/

**Comment by momdo** [comment]
@kazuhito-kidachi 
コメントありがとうございます…！
まだ斜め読みしかできてませんが、CSS Trickの記事強そうですね…。

**Comment by bakera** [comment]
これはもし入れるならARIAを紹介する4-2で扱うのが良さそうです。

**Comment by momdo** [comment]
@bakera 
ハンバーガーメニューで扱えていると思いますので、Closeします（必要であればreopenください）
https://github.com/bakera/html-book/blob/master/md_text/4-4.md#%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89%E6%93%8D%E4%BD%9C%E3%82%92%E5%8F%AF%E8%83%BD%E3%81%AB%E3%81%99%E3%82%8B
